<?php

$catalogoFormatos=[

"SIC"=>"CATALOGO DE CENTROS DE TRABAJO",
"CONAPO_POR_MUNICIPIOS"=>"CONAPO POR MUNICIPIOS",
"CONAPO_POR_EDADES"=>"CONAPO POR EDADES",

"CAM"=>"EDUCACION ESPECIAL CENTRO DE ATENCION MULTIPLE",
"CEBAS"=>"CEBAS",
"FORMACION PARA EL TRABAJO"=>"FORMACION PARA EL TRABAJO",
"USAER"=>"EDUCACION ESPECIAL UNIDAD DE SERVICIOS DE APOYO A LA EDUCACION REGULAR",

"INICIAL_GENERAL"=>"EDUCACION INICIAL",
"INICIAL_INDIGENA"=>"EDUCACION INICIAL INDIGENA",
"INICIAL_NO_ESCOLARIZADA"=>"EDUCACION INICIAL NO ESCOLARIZADA",
"INICIAL_COMUNITARIA"=>"INICIAL COMUNITARIA",
"INICIAL_PRIMERA_INFANCIA"=>"CENTROS COMUNITARIOS DE ATENCION A LA PRIMERA INFANCIA",

"PREESCOLAR_GENERAL"=>"EDUCACION PREESCOLAR",
"PREESCOLAR_INDIGENA"=>"EDUCACION PREESCOLAR INDIGENA",
"PREESCOLAR_COMUNITARIA"=>"PREESCOLAR COMUNITARIA",

"PRIMARIA_GENERAL"=>"EDUCACION PRIMARIA",
"PRIMARIA_INDIGENA"=>"EDUCACION PRIMARIA INDIGENA",
"PRIMARIA_COMUNITARIA"=>"PRIMARIA COMUNITARIA",

"SECUNDARIA_GENERAL"=>"EDUCACION SECUNDARIA",
"SECUNDARIA_COMUNITARIA"=>"SECUNDARIA COMUNITARIA",

"MEDIA SUPERIOR_GENERAL"=>"ESTADISTICA DE EDUCACION MEDIA SUPERIOR BACHILLERATO GENERAL",
"MEDIA SUPERIOR_TECNOLOGICO"=>"ESTADISTICA DE EDUCACION MEDIA SUPERIOR POR CARRERA",
"MEDIA SUPERIOR_PLANTEL"=>"ESTADISTICA DE EDUCACION MEDIA SUPERIOR POR PLANTEL",

"SUPERIOR_LICENTIATURA"=>"ESTADISTICA DE EDUCACION SUPERIOR POR CARRERA",
"SUPERIOR_POSGRADO"=>"ESTADISTICA DE EDUCACION SUPERIOR POR POSGRADO",
"SUPERIOR_INSTITUCION"=>"ESTADISTICA DE EDUCACION SUPERIOR POR INSTITUCION",
"SUPERIOR_ESCUELAS"=>"ESTADISTICA DE EDUCACION SUPERIOR POR ESCUELA",

"UBBJ_CARRERAS"=>"UNIVERSIDAD PARA EL BIENESTAR BENITO JUAREZ, POR CARRERAS",
"UBBJ_ESCUELAS"=>"UNIVERSIDAD PARA EL BIENESTAR BENITO JUAREZ, POR ESCUELAS",
"UBBJ_INSTITUCION"=>"UNIVERSIDAD PARA EL BIENESTAR BENITO JUAREZ, POR INSTITUCION",

"ANEXO_DE_COMPUTO"=>"ANEXO DE RECURSOS VISUALES	COMPUTACIONES Y AUDIOVISUALES",
"ANEXO_SOSTENIBLE"=>"ATENCION A LOS OBJETIVOS DE DESARROLLO SOSTENIBLE",

];